'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import Navigation from '@/components/Navigation'

interface ProfileUser { id: string; email: string; name: string; bio?: string | null }

export default function ProfilePage() {
  const [user, setUser] = useState<ProfileUser | null>(null); const [name, setName] = useState(''); const [bio, setBio] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState('')
  useEffect(() => { fetch('/api/auth/me').then((res) => res.json()).then((data) => { if (data.user) { setUser(data.user); setName(data.user.name); setBio(data.user.bio || '') } else setError('Bạn cần đăng nhập để xem hồ sơ.') }) }, [])
  async function saveProfile(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); const res = await fetch('/api/auth/me', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, bio }) }); const data = await res.json(); if (!res.ok) setError(data.error); else { setUser(data.user); setMessage('Đã lưu hồ sơ.') } }
  async function changePassword(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); const res = await fetch('/api/auth/password', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ currentPassword, newPassword }) }); const data = await res.json(); if (!res.ok) setError(data.error); else { setCurrentPassword(''); setNewPassword(''); setMessage('Đã đổi mật khẩu.') } }
  return <div className="min-h-screen bg-slate-950 text-slate-100"><Navigation /><main className="mx-auto max-w-2xl space-y-6 px-4 py-10"><Link href="/discover" className="text-sm text-slate-400 hover:text-white">← Quay lại khám phá</Link><h1 className="text-3xl font-extrabold text-white">Hồ sơ tài khoản</h1>{error && <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</div>}{message && <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300">{message}</div>}{user && <><form onSubmit={saveProfile} className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-bold text-white">Thông tin cá nhân</h2><input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Họ tên" /><input value={user.email} readOnly className="w-full rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-slate-500" /><textarea value={bio} onChange={(event) => setBio(event.target.value)} className="min-h-28 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Giới thiệu" /><button className="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold hover:bg-indigo-500">Lưu thay đổi</button></form><form onSubmit={changePassword} className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-bold text-white">Đổi mật khẩu</h2><input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Mật khẩu hiện tại" /><input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} required minLength={8} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Mật khẩu mới (tối thiểu 8 ký tự)" /><button className="rounded-xl bg-rose-600 px-4 py-3 text-sm font-bold hover:bg-rose-500">Đổi mật khẩu</button></form></>}</main></div>
}
